github: [blueset]
ko_fi: blueset
liberapay: blueset
custom:
- https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=ilove%401a23.com&item_name=Buy+Eana+a+cup+of+coffee&currency_code=USD&source=url
