"preserve_hierarchy": true

files: [
  {
    "source" : "/EFBChannels/efb-gpg-middleware/efb_gpg_middleware/locale/*.pot",
    "translation" : "/EFBChannels/efb-gpg-middleware/efb_gpg_middleware/locale/%locale_with_underscore%/LC_MESSAGES/%file_name%.po",
  },
]